services:
  frontend:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ../frontend:/usr/share/nginx/html:ro
    networks:
      - app-network

  user-db:
    image: mongo
    volumes:
      - user_data:/data/db
    networks:
      - app-network

  product-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ../Prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

volumes:
  user_data:
  product_data:

networks:
  app-network: