apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: profjigisha/worker:latest  
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: WORKER_CONCURRENCY
              value: "5"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: worker-db
              mountPath: /app/data
      volumes:
        - name: worker-db
          persistentVolumeClaim:
            claimName: worker-db-data

