global:
  resolve_timeout: 5m

route:
  receiver: 'team-email'

receivers:
  - name: 'team-email'
    email_configs:
    - to: 'team@example.com'
      from: 'alertmanager@example.com'
      smarthost: 'smtp.example.com:587'
      auth_username: 'smtp-user'
      auth_password: 'smtp-password'
      send_resolved: true

  - name: 'team-slack'
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
      channel: '#alerts'
      send_resolved: true